### ISSUE TITLE
管理后台图片显示不了，如下图

### ISSUE THREAD

**Issue by LianWilliam** [hui-ho/WebStack-Laravel#11]
![image](https://user-images.githubusercontent.com/35838730/54866803-78a3db80-4db3-11e9-8a97-f0e82c380850.png)

**Comment by hkylin** [comment]
修改文件.env中的“APP_URL=”字段即可

**Comment by usairaq** [comment]
> 修改文件.env中的“APP_URL=”字段即可

这个好像必须写部署网站的域名，我用了localhost也不好用
