### ISSUE TITLE
管理后台分类管理新增了一个导航分类，拖动到第一个位置后保存，实际显示位置并不在第一个位置上

### ISSUE THREAD

**Issue by LianWilliam** [hui-ho/WebStack-Laravel#12]
![image](https://user-images.githubusercontent.com/35838730/54866937-ca4d6580-4db5-11e9-80c7-3f8f262ca710.png)

并且新建的网址离上一个分类有很多空白：
![image](https://user-images.githubusercontent.com/35838730/54866981-3d56dc00-4db6-11e9-82b0-218d1fff4f52.png)

**Comment by hkylin** [comment]
前台展示用了foreach 貌似不能排序....
