### ISSUE TITLE
执行php artisan migrate:refresh --seed时报错

### ISSUE THREAD

**Issue by johntaiii** [hui-ho/WebStack-Laravel#19]
如图所示：报PHP Fatal error:  Class 'PDO' not found in /root/workspace/webstack/WebStack-Laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 1236

![](http://snappyimages.nextwavesrl.netdna-cdn.com/img/2f23a9df5e705c6c0b9eed539e084162.png)

请问是哪个步骤操作不对吗？

**Comment by hui-ho** [comment]
请执行 ```php -m``` 查看 PDO 扩展是否已经安装.

**Comment by johntaiii** [comment]
恩，PDO扩展没有安装，现在可以了，谢谢
