### ISSUE TITLE
部署后，管理后台静态文件加载失败，请求地址还是http://localhost:8000，.env中APP_URL已经改成了域名，请问哪边还需要修改？

### ISSUE THREAD

**Issue by johntaiii** [hui-ho/WebStack-Laravel#22]
![image](https://user-images.githubusercontent.com/2558009/59175520-6c484700-8b88-11e9-9157-550044e3bd4b.png)

**Comment by wzh154710510** [comment]
找到解决方法了吗

**Comment by johntaiii** [comment]
> 找到解决方法了吗

还没有

**Comment by wzh154710510** [comment]
我跟你 遇到的问题一样，他监听的是127.0.0.1:8000    外网访问不了

**Comment by wzh154710510** [comment]
成功了 要用nginx 
![image](https://user-images.githubusercontent.com/23711162/59179308-3315d400-8b94-11e9-9645-f3e3b4f93e82.png)

**Comment by johntaiii** [comment]
> 成功了 要用nginx
> ![image](https://user-images.githubusercontent.com/23711162/59179308-3315d400-8b94-11e9-9645-f3e3b4f93e82.png)

管理后台资源能正常加载吗

**Comment by wzh154710510** [comment]
> > 成功了 要用nginx
> > ![image](https://user-images.githubusercontent.com/23711162/59179308-3315d400-8b94-11e9-9645-f3e3b4f93e82.png)
> 
> 管理后台资源能正常加载吗

正常

**Comment by johntaiii** [comment]
> > > 成功了 要用nginx
> > > ![image](https://user-images.githubusercontent.com/23711162/59179308-3315d400-8b94-11e9-9645-f3e3b4f93e82.png)
> > 
> > 
> > 管理后台资源能正常加载吗
> 
> 正常

请问nginx怎么配置的？能贴下吗？我打开首页是正常的，但是访问管理后台，就自动跳转到localhost:8000

**Comment by johntaiii** [comment]
> > > > 成功了 要用nginx
> > > > ![image](https://user-images.githubusercontent.com/23711162/59179308-3315d400-8b94-11e9-9645-f3e3b4f93e82.png)
> > > 
> > > 
> > > 管理后台资源能正常加载吗
> > 
> > 
> > 正常
> 
> 请问nginx怎么配置的？能贴下吗？我打开首页是正常的，但是访问管理后台，就自动跳转到localhost:8000

可以了，之前nginx配置的有问题。

**Comment by rainbig** [comment]
> > > > > 成功了 要用nginx
> > > > > ![image](https://user-images.githubusercontent.com/23711162/59179308-3315d400-8b94-11e9-9645-f3e3b4f93e82.png)
> > > > 
> > > > 
> > > > 管理后台资源能正常加载吗
> > > 
> > > 
> > > 正常
> > 
> > 
> > 请问nginx怎么配置的？能贴下吗？我打开首页是正常的，但是访问管理后台，就自动跳转到localhost:8000
> 
> 可以了，之前nginx配置的有问题。

请问您怎么配置的nginx呀？
