### ISSUE TITLE
作者：有没有人能告诉我为什么这几天这么多人star？

### ISSUE THREAD

**Issue by hui-ho** [hui-ho/WebStack-Laravel#24]
有点矇了。。。😳

**Comment by johntaiii** [comment]
即刻过来的

**Comment by wzh154710510** [comment]
被github 推荐到热门项目了。就跑过来了。加油

**Comment by johntaiii** [comment]
楼主可以建个群，方便交流。

**Comment by CharlesYe8848** [comment]
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to undefined function Intervention\Image\Gd\imagettfbbox()

**Comment by CharlesYe8848** [comment]
后台验证码登录那里显示不出来验证码图片，无法登录

**Comment by ZHDeveloper** [comment]
我的也是，后台登录验证码出不来。

**Comment by AWhiteMouse** [comment]
掘金来的
