### ISSUE TITLE
如何修改网站相关介绍信息？

### ISSUE THREAD

**Issue by johntaiii** [hui-ho/WebStack-Laravel#25]
比如网站首页Logo，关于本站页面的内容等

**Comment by luomoxu** [comment]
laravel-admin 官方demo里面有个设置功能 可以考虑移植过来
https://demo.laravel-admin.org/forms/settings

**Comment by hui-ho** [comment]
已添加配置管理模块，可按需配置https://github.com/laravel-admin-extensions/config

**Comment by johntaiii** [comment]
> 已添加配置管理模块，可按需配置https://github.com/laravel-admin-extensions/config

请问如何更新？git pull
