### ISSUE TITLE
部署后，只能在本机通过http://127.0.0.1:8000访问，局域网的其他机器访问不了，这个怎么解决

### ISSUE THREAD

**Issue by LianWilliam** [hui-ho/WebStack-Laravel#3]
部署后，只能在本机通过http://127.0.0.1:8000访问，局域网的其他机器访问不了，这个怎么解决

Centos 7 部署的，防火墙已关闭。本机通过：curl http://127.0.0.1:8000 访问没问题

通过当前服务器IP curl http://10.10.10.99:8000  获取局域网其他机器浏览器输入http://10.10.10.99:8000就访问不了，这个是什么问题呢？

**Comment by hui-ho** [comment]
可以参考 Laravel 的部署文档：https://learnku.com/docs/laravel/5.5/deployment/1287

**Comment by LianWilliam** [comment]
> 可以参考 Laravel 的部署文档：https://learnku.com/docs/laravel/5.5/deployment/1287

你说的这个链接里，没有看到能够解决我问题的地方诶？能否详细说下在哪里？

**Comment by jiespring** [comment]
如何解决的？

**Comment by LianWilliam** [comment]
目前还没有解决，作者没有答复，发出的链接中没有看到解决方案。

**Comment by Gourds** [comment]
@LianWilliam @jiespring 
```
php artisan serve  --host=0.0.0.0 --port=8000
```
有Nginx的话，当然可以考虑配置Proxy

**Comment by keepthinkingit** [comment]
lnmp 经典配置 . 环境搭建后按照教程配好 nginx config . 还不会就谷狗搜索 lnmp 建站 .
