### ISSUE TITLE
自己（小白）使用宝塔面板部署教程

### ISSUE THREAD

**Issue by Spoience** [hui-ho/WebStack-Laravel#49]
你好，我是个小白，这个项目非常棒！这是我使用宝塔面板部署过程https://www.spoience.top/archives/25.html
中间出了点问题，自己Google了下，最后弄好了，希望给予参考😋

**Comment by wlibai** [comment]
打不开了。

**Comment by Spoience** [comment]
> 打不开了。

之前搬博客😂https://spoience.top/archives/14.html
