### ISSUE TITLE
网页上的php DebugBar调试工具应该怎么关闭呢？

### ISSUE THREAD

**Issue by kang-mk** [hui-ho/WebStack-Laravel#58]
![image](https://user-images.githubusercontent.com/20243226/84039402-c403d300-a9d3-11ea-84c3-9170a714281f.png)
网页上的php DebugBar调试工具应该怎么关闭呢？

**Comment by cklx0719** [comment]
修改根目录下.env文件：
将
```
APP_DEBUG=true
```
修改为
```
APP_DEBUG=false
```

**Comment by kang-mk** [comment]
搞定了 非常感谢  我是用docker搭建的，直接指定一下APP_DEBUG的变量就可以了
